export default {
  customers: [
    {
      id: "a3s",
      name: "Amina khan",
      time: "1 day ago",
      amount: 200,
      borrow: false,
      trades: [
        { date: "08/08/2021", amount: 100, borrow: true },
        { date: "08-08-2021", amount: 300, borrow: false },
        { date: "08-08-2021", amount: 500, borrow: true },
        { date: "08-08-2021", amount: 200, borrow: false },
        { date: "08-08-2021", amount: 400, borrow: false },
        { date: "08-08-2021", amount: 100, borrow: true },
        { date: "08-08-2021", amount: 50, borrow: false },
        { date: "08-08-2021", amount: 100, borrow: true },
        { date: "08-08-2021", amount: 1000, borrow: false },
        { date: "08-08-2021", amount: 1200, borrow: true },
        { date: "08-08-2021", amount: 1050, borrow: true },
      ],
    },
    {
      id: "a2s",
      name: "Shahroon",
      time: "2 day ago",
      amount: 500,
      borrow: true,
    },
    {
      id: "bsd3",
      name: "Taimur",
      time: "4 day ago",
      amount: 400,
      borrow: true,
    },
    {
      id: "ad32",
      name: "Naveed",
      time: "4 day ago",
      amount: 400,
      borrow: false,
    },
    {
      id: "ssdf",
      name: "Hazrat amin",
      time: "4 day ago",
      amount: 400,
      borrow: true,
    },
    {
      id: "xvs",
      name: "Jalil",
      time: "5 day ago",
      amount: 800,
      borrow: true,
    },
    {
      id: "sdfxc",
      name: "Jalil",
      time: "5 day ago",
      amount: 800,
      borrow: true,
    },
    {
      id: "sdfgfhfghsf",
      name: "Jalil",
      time: "5 day ago",
      amount: 800,
      borrow: true,
    },
    {
      id: "xvwe",
      name: "Jalil",
      time: "5 day ago",
      amount: 800,
      borrow: true,
    },
    {
      id: "xvcxcv",
      name: "Jalil",
      time: "5 day ago",
      amount: 800,
      borrow: true,
    },
  ],
};
